# Numba Lab

Now it's your turn!

Your challenge is to implement Fizz Buzz in CUDA Python with numba and calculate all instances of `Fizz`, `Buzz` and `Fizz Buzz` for the numbers between `1` and `50_000_000`.

Before you begin, please turn off Google Colab's autocompletion by going to the settings gear in the top right -> Editor -> Uncheck "Automatically trigger code completions"

In [1]:
import numpy as np
from numba import cuda

**1. Create the input data array.** Try using `np.arange`.

In [3]:
data = np.arange(1, 50_000_001)
data

array([       1,        2,        3, ..., 49999998, 49999999, 50000000])

**2. Create the output data array.**

In [4]:
output = np.zeros_like(data)
output

array([0, 0, 0, ..., 0, 0, 0])

**3. Calculate the number of threads and blocks.**

In [19]:
import math

threads = 128
blocks = math.ceil(data.shape[0] / threads)
blocks

390625

**4. Create the kernel.** _Tip: Our output array must be numeric so try using the values `1`, `2` and `3` to represent `Fizz`, `Buzz` and `Fizz Buzz`._

In [20]:
@cuda.jit
def fizz_buzz(input_array, output_array):
    i = cuda.grid(1)
    if input_array[i]%3==0:
      output_array[i] = 1
    if input_array[i]%5==0:
      output_array[i] = 2
    if input_array[i]%3==0 and input_array[i]%5==0:
      output_array[i] = 3

fizz_buzz[blocks, threads](data, output)
output[0:100]

/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/devicearray.py:886: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))


array([0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 3, 0, 0, 1, 0, 2, 1, 0,
       0, 1, 2, 0, 1, 0, 0, 3, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0,
       3, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 3, 0, 0, 1, 0, 2, 1,
       0, 0, 1, 2, 0, 1, 0, 0, 3, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 0,
       0, 3, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2])

**5. Run our kernel.**

In [21]:
%%time
fizz_buzz[blocks, threads](data, output)
output[:12]

CPU times: user 343 ms, sys: 2.22 ms, total: 345 ms
Wall time: 345 ms


array([0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1])

**Extra Credit 6. Calculate the highest instance of `Fizz`.**

In [ ]:
idx = ...
data[idx]